[package]
name = "Exocryption"
version = "0.0.1"
authors = ["exo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rust-crypto = "^0.2"
data-encoding = "^2.3.2"
rand = "^0.6.0"
serde_json = "^1.0.59"
serde = { version = "1.0", features = ["derive"] }
